<?php
require_once('View/template/header.phtml'); ?>
    <link href="/css/bootstrap.css" rel="stylesheet">

    <!-- Bootstrap theme -->
    <link href="/css/bootstrap-theme.css" rel="stylesheet">
    <link href="/css/styles.css" rel="stylesheet">

    <!-- displays title background image -->
<div class="container">
    <div id="pageHeader" class="jumbotron text-xl-center">
        <h1>Welcome to Auction System!</h1>
        <img class="fluid" src="images/auction main.jpg"/>
    </div>
</div>


<?php
require_once('View/template/footer.phtml'); ?>